### PR TITLE
add documentation for deprecating master

### PR DESCRIPTION
**Pull request by andreeaflorescu**
GitHub changed the default branch name to main. We should also follow
the example and rename the existing branches. As there are consumers of
rust-vmm that use the master branch in their products, we need to mark
it as deprecated instead of simply renaming it to main.

### CODE REVIEW

**Comment by andreeaflorescu** [comment]
@rbradford that was my initial thought as well, but then when we discussed about this in the sync meeting @sboeuf suggested we keep both because you are consuming the `master` branch, and that might break your (or other customers) build.

If that is not the case, I more than happy to just rename the branch. That also comes with the advantage that I don't have to manually add PRs to all rust-vmm repositories to deprecate master, because master would no longer exist.

**Comment by rbradford** [comment]
> @rbradford that was my initial thought as well, but then when we discussed about this in the sync meeting @sboeuf suggested we keep both because you are consuming the `master` branch, and that might break your (or other customers) build.

@sboeuf When you made that comment about keeping the branch were you aware of the GitHub redirect behaviour when you rename a branch?

**Comment by sboeuf** [comment]
@sboeuf When you made that comment about keeping the branch were you aware of the GitHub redirect behaviour when you rename a branch?

No I wasn't. So I definitely think we can go ahead and remove `master`.

**Comment by andreeaflorescu** [comment]
Awesome :confetti_ball: I'll just then go ahead and rename all branches. This will also help with the CI, as keeping both master and main working is a bit challenging at the moment. Closing this.

**Pull request closed without merging**
